#!/usr/bin/env bash

if [[ "$SPIN" = 1 ]]
then
  # Only run nested steps in Spin + shopify/shopify workspaces.
  if [[ "$SPIN_REPO_SOURCE_PATH" = "/src/github.com/shopify/shopify" ]]
  then
    cd "$SPIN_REPO_SOURCE_PATH"
    cartridge insert thetrevorharmon/setup-shopify-config
    /cartridges/shopify-reportify-config/setup.sh

    restart
  fi
fi
